

### SIGN UP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "spotted.vietnam@gmail.com",
  "password": "123456",
  "name": "Hậu"
}


### CONFIRM EMAIL
GET http://localhost:3000/auth/confirm/sfjsdm



### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "spotted.vietnam@gmail.com",
  "password": "123456"
}

### RESET PASSWORD
POST http://localhost:3000/auth/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjljZjk5ZGFhNzUzZWIyMWEzYTllMjgiLCJpYXQiOjE3MjE5ODg1NTl9.hHPQTioqRI0_uG8FIH7u6Plxa9qpTrDUbwypqO_Mzuk

{
  "oldPassword": "123456",
  "newPassword": "123456"
}

### FORGOT PASSWORD
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "caynhat05062004@gmail.com"
}

### GET PROFILE
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjljZjk5ZGFhNzUzZWIyMWEzYTllMjgiLCJpYXQiOjE3MjE4Mjk5OTV9.7lTXJ3ltagC5MxXIZKoUrjOPnYVTkqUavhW1f8rewa0

### UPDATE PROFILE
PUT http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjljZjk5ZGFhNzUzZWIyMWEzYTllMjgiLCJpYXQiOjE3MjE4Mjk5OTV9.7lTXJ3ltagC5MxXIZKoUrjOPnYVTkqUavhW1f8rewa0
  
{
  "isVerified": false,
  "name": "Hehe",
  "phone": "012345",
  "interests": ["chess"]
}

### UPDATE AVATAR
PUT http://localhost:3000/auth/profile/avatar
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjljZjk5ZGFhNzUzZWIyMWEzYTllMjgiLCJpYXQiOjE3MjE4Mjk5OTV9.7lTXJ3ltagC5MxXIZKoUrjOPnYVTkqUavhW1f8rewa0





### GET PUBLIC PROFILE
GET http://localhost:3000/users/66a39662a7e21e8958e46f3e

