
### SIGN UP
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "caynhat05062004@gmail.com",
  "password": "123456",
  "name": "Hậu"
}


### CONFIRM EMAIL
GET http://localhost:3000/auth/confirm/sfjsdm



### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "caynhat05062004@gmail.com",
  "password": "123456"
}

### GET PROFILE
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjljOWU3YWYyYWY0MDY0M2ZjYTZlYTIiLCJpYXQiOjE3MjE1NDAyNDB9.gT5lGJjORJdAivemmVehEbk3EZHabwkT7bU5GQPYE9I

### UPDATE PROFILE
PUT http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjljOWU3YWYyYWY0MDY0M2ZjYTZlYTIiLCJpYXQiOjE3MjE1NDAyNDB9.gT5lGJjORJdAivemmVehEbk3EZHabwkT7bU5GQPYE9I
  
{
  "name": "Hậu",
  "phone": "012",
  "interests": ["chess"]
}

### GET PUBLIC PROFILE
GET http://localhost:3000/users/669cf99daa753eb21a3a9e28