openapi: 3.0.0
info:
  title: Event API
  description: API for creating events
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /events/create:
    post:
        summary: Create a new event
        description: Endpoint to create a new event with details like description, start time, duration, and location.
        requestBody:
            required: true
            content:
            application/json:
                schema:
                type: object
                properties:
                    description:
                        type: string

